-- Add a Costing Review stage (between Costing and Offer Released) and a
-- Costing Review document kind.
ALTER TABLE `Enquiry`
  MODIFY COLUMN `stage` ENUM('NEW', 'CONTACTED', 'REVIEW', 'CONCEPT', 'COSTING', 'COSTING_REVIEW', 'OFFER_RELEASED', 'FOLLOW_UP', 'WON', 'LOST') NOT NULL DEFAULT 'NEW';
ALTER TABLE `EnquiryStageEvent`
  MODIFY COLUMN `from_stage` ENUM('NEW', 'CONTACTED', 'REVIEW', 'CONCEPT', 'COSTING', 'COSTING_REVIEW', 'OFFER_RELEASED', 'FOLLOW_UP', 'WON', 'LOST') NULL;
ALTER TABLE `EnquiryStageEvent`
  MODIFY COLUMN `to_stage` ENUM('NEW', 'CONTACTED', 'REVIEW', 'CONCEPT', 'COSTING', 'COSTING_REVIEW', 'OFFER_RELEASED', 'FOLLOW_UP', 'WON', 'LOST') NOT NULL;
ALTER TABLE `EnquiryAttachment`
  MODIFY COLUMN `kind` ENUM('FORMAT_PDF', 'FORMAT_EXCEL', 'CONCEPT', 'POWER_CALC', 'COSTING', 'COSTING_REVIEW', 'OFFER') NOT NULL;
