-- Add a Negotiation stage after Offer Released.
ALTER TABLE `Enquiry`
  MODIFY COLUMN `stage` ENUM('NEW', 'CONTACTED', 'REVIEW', 'CONCEPT', 'COSTING', 'COSTING_REVIEW', 'OFFER_RELEASED', 'NEGOTIATION', 'WON', 'LOST') NOT NULL DEFAULT 'NEW';
ALTER TABLE `EnquiryStageEvent`
  MODIFY COLUMN `from_stage` ENUM('NEW', 'CONTACTED', 'REVIEW', 'CONCEPT', 'COSTING', 'COSTING_REVIEW', 'OFFER_RELEASED', 'NEGOTIATION', 'WON', 'LOST') NULL;
ALTER TABLE `EnquiryStageEvent`
  MODIFY COLUMN `to_stage` ENUM('NEW', 'CONTACTED', 'REVIEW', 'CONCEPT', 'COSTING', 'COSTING_REVIEW', 'OFFER_RELEASED', 'NEGOTIATION', 'WON', 'LOST') NOT NULL;
ALTER TABLE `EnquiryActivity`
  MODIFY COLUMN `stage` ENUM('NEW', 'CONTACTED', 'REVIEW', 'CONCEPT', 'COSTING', 'COSTING_REVIEW', 'OFFER_RELEASED', 'NEGOTIATION', 'WON', 'LOST') NULL;
